# Generated by Django 2.1.4 on 2018-12-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('menu', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('include_taxes_in_prices', models.BooleanField(default=True)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('charge_taxes_on_shipping', models.BooleanField(default=True)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('default_weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz'), ('g', 'g')], default='kg', max_length=10)),
                ('bottom_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
                ('homepage_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Collection')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
            ],
            options={
                'permissions': (('manage_settings', 'Manage settings.'),),
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site.SiteSettings')),
            ],
        ),
        migrations.AddField(
            model_name='authorizationkey',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='sitesettingstranslation',
            unique_together={('language_code', 'site_settings')},
        ),
        migrations.AlterUniqueTogether(
            name='authorizationkey',
            unique_together={('site_settings', 'name')},
        ),
    ]
